apiVersion: v1
kind: Pod
metadata:
  name: test12
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: default
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/tmp"
          name: task-pv-storage
  nodeSelector:
          test: demo
